### ISSUE TITLE
Fingerprint not registering

### ISSUE THREAD

**Issue by Mahamuds9990** [TJ-Releases/fajita#1]
![Screenshot_20240601-040610_Settings](https://github.com/TJ-Releases/fajita/assets/171389238/12c3cd48-fd51-496a-8c79-ae6ded57f2ec)
I've tried several times to enroll my fingerprints but it failed every time,with the prompt shown in the above screenshot, please give me a solution.

**Comment by TJ-Releases** [comment]
This repository/org is for releases only and I don't check here for people reporting issues.

That said, this is not a common problem, and seems to be particular to your personal device hardware/software configuration. In general, all current releases of crDroid 9.x and 10.x are capable of enrolling multiple fingerprints just fine.

If you'd like help with your issue, please join one of the proper support channels (the XDA forum thread or Telegram group) as linked from the download page for your device on the official website, https://crdroid.net, and be prepared to answer some questions about your hardware & software setup, and to provide logs.
